### ISSUE TITLE
silence on screen messages when model is running

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#23]

**Comment by Rasilgon** [comment]
I see here two aspects:
1. **Message types:** : 
   In the package, there are messages that are displayed with _cat_. The reason is that currently messages, warnings and errors all have a red color in the console. This is can be confusing if a lot of text is output.  On the other hand, using cat or print statements is not an ideal programming practice for displaying function/package messages. For such a task there is message statement. 
2. **Supressing messages (in general)**: 
   If we replace _cat_ statements by _message_ suppressing,  the task is as simple as:
   `suppressMessages(result <-   runLPJ(mainDir, settings= settings))`
   and no message will be displayed. This does not affect warnings. 

If we decide to remove cat statements, I think that it should be up to users whether to display the message or not.  _suppressMessages_ is a standard R function (https://stat.ethz.ch/R-manual/R-devel/library/base/html/message.html).  If we decide to keep the _cat_ statements,  suppressing messages would require that we implement in the package a function (if ... ) to handle each single _cat_ statement.

**Comment by mauriziobagnara** [comment]
let's try replacing cat statements by message

**Comment by Rasilgon** [comment]
This is done. I replaced  cat statements by message.
