### ISSUE TITLE
Check if outputs are written

### ISSUE THREAD

**Issue by florianhartig** [biometry/RLPJ#35]
Not a priority, but would be good to check if outputs are actually written, to avoid reading in outputs from a previous run

**Comment by Rasilgon** [comment]
The runLPJ has an option in settings to define what should be done with the output files: "delete".
If it is set to TRUE, the outputs are deleted after they have been read in. Therefore, the outputs from a previous run wont't be read in the next one because they do no longer exist.

If they were no outputs (or they can't be read), the package (getLPJData) will raise a stop call 
`stop("Model outputs are not readable")`

If the user is running the model using an existing folder with output files for previous model runs, the situation is more complicated. In the case that the model could not produce output files, and as long as it doesn't crash, the package will read the previous files.  This is a problem for the use. Yet, I would say, before calling the model, the user should know what is in the folder he/she is setting as working directory for the model runs.

However, to avoid this situation we could include a check in package, and delete any previous files in the output directory. This is can be easily done.

**Comment by mauriziobagnara** [comment]
Solved
